using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace realmabilities_atlasOF._temporary_helper
{
    class DB_RealmAbilities_Scripts
    {
        // --------------------------------------------------------------------------------
        // ---------- DATABASE SCRIPT TO RUN FOR NEW ATLAS REALM ABILITIES TABLE ----------
        // ----------               ClassXRealmAbility_Atlas                     ----------
        // --------------------------------------------------------------------------------
        /*

        -- DEFAULT GAME DATABASE SETTINGS FOR TESTING PURPOSES ----------------------------
        UPDATE `atlas`.`serverproperty` SET `DefaultValue`='True', `Value`='True' WHERE  `Key`='disable_quit_timer';

        -- DROP EXISTING TABLE IF ALREADY EXISTS ------------------------------------------
        DROP TABLE IF EXISTS `classxrealmability_atlas`;


        -- CREATE NEW EMPTY TABLE ---------------------------------------------------------
        CREATE TABLE `classxrealmability_atlas` (
        `CharClass` INT(11) NOT NULL,
        `AbilityKey` TEXT NOT NULL COLLATE 'latin1_swedish_ci',
        `LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00',
        `ClassXRealmAbility_Atlas_ID` VARCHAR(255) NOT NULL COLLATE 'latin1_swedish_ci',
        PRIMARY KEY (`ClassXRealmAbility_Atlas_ID`) USING BTREE
        )
        COLLATE='latin1_swedish_ci'
        ENGINE=MyISAM
        ;

        -- DELETE ALL AtlasOF abilities to keep db consistent keys during development
        DELETE FROM `ability` WHERE `AbilityID` > 240;


        -- ADD REALM ABILITES IN TABLE: ability
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('241','AtlasOF_MCL','Mystic Crystal Lore','501','Grants a refresh of power based on the percentages listed. Cannot be used when in combat.','3008','DOL.GS.RealmAbilities.AtlasOF_MysticCrystalLoreAbility','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('242','AtlasOF_Purge','Purge','502','Removes all negative effects but leaves any applicable immunity timers in place.','3010','DOL.GS.RealmAbilities.AtlasOF_PurgeAbility','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('243','AtlasOF_AugStr','Augmented Strength','503','Increases Strength by the listed amount per level.','0','DOL.GS.RealmAbilities.AtlasOF_RAStrengthEnhancer','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('244','AtlasOF_AugDex','Augmented Dexterity','504','Increases Dexterity by the listed amount per level.','0','DOL.GS.RealmAbilities.AtlasOF_RADexterityEnhancer','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('245','AtlasOF_AugCon','Augmented Constitution','505','Increases Constitution by the listed amount per level.','0','DOL.GS.RealmAbilities.AtlasOF_RAConstitutionEnhancer','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('246','AtlasOF_AugQui','Augmented Quickness','506','Increases Quickness by the listed amount per level.','0','DOL.GS.RealmAbilities.AtlasOF_RAQuicknessEnhancer','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('247','AtlasOF_AugAcuity','Augmented Acuity','507','Increases primary casting stat by the listed amount per level.','0','DOL.GS.RealmAbilities.AtlasOF_RAAcuityEnhancer','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('248','AtlasOF_LongWind','Long Wind','508','Decreases the amount of endurance taken per tick when sprinting, by the number listed.','0','DOL.GS.RealmAbilities.AtlasOF_LongWindAbility','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('249','AtlasOF_MasteryOfPain','Mastery of Pain','509','Increases chance to deal a critical hit in melee per listed percentage. (Passes on to Necro Pets)','0','DOL.GS.RealmAbilities.AtlasOF_MasteryOfPain','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('250','AtlasOF_MasteryOfParrying','Mastery of Parrying','510','Increases chance to parry by the listed percentage.','0','DOL.GS.RealmAbilities.AtlasOF_MasteryOfParrying','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('251','AtlasOF_MasteryOfBlocking','Mastery of Blocking','511','Increases chance to block by the listed percentage.','0','DOL.GS.RealmAbilities.AtlasOF_MasteryOfBlocking','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('252','AtlasOF_MasteryOfArms','Mastery of Arms','512','Increases melee attack speed by the listed percentage.','0','DOL.GS.RealmAbilities.AtlasOF_MasteryOfArms','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('253','AtlasOF_MasteryOfMagery','Mastery of Magery','513','Additional effectiveness of magical damage by listed percentage.','0','DOL.GS.RealmAbilities.AtlasOF_MasteryOfMagery','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('254','AtlasOF_MasteryOfArchery','Mastery of Archery','514','Increases bow firing speed by the listed percentage.','0','DOL.GS.RealmAbilities.AtlasOF_MasteryOfArchery','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('255','AtlasOF_MasteryOfWater','Mastery of Water','515','Increases swimming speed by the listed percentage.','0','DOL.GS.RealmAbilities.AtlasOF_MasteryOfWater','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('256','AtlasOF_MasteryOfTheArt','Mastery of the Art','516','Increases spellcasting speed by the listed percentage.','0','DOL.GS.RealmAbilities.AtlasOF_MasteryOfTheArt','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('257','AtlasOF_MasteryOfTheArcane','Mastery of the Arcane','517','Increases effectiveness of your buff spells by the listed percentage.','0','DOL.GS.RealmAbilities.AtlasOF_MasteryOfTheArcane','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('258','AtlasOF_MasteryOfHealing','Mastery of Healing','518','Increases the effectiveness of healing spells by the listed percentage.','0','DOL.GS.RealmAbilities.AtlasOF_MasteryOfHealing','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('259','AtlasOF_WildPower','Wild Power','519','Increases chance to deal a critical hit with all spells that do damage, including DoTs, by listed percentage.','0','DOL.GS.RealmAbilities.AtlasOF_WildPowerAbility','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('260','AtlasOF_WildMinion','Wild Minion','520','Increases chance of pet dealing a critical hit with melee, archery, or spells, by the listed percentage.','0','DOL.GS.RealmAbilities.AtlasOF_WildMinionAbility','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('261','AtlasOF_WildHealing','Wild Healing','521','Adds the listed percentage chance to critical heal on each target of a heal spell.','0','DOL.GS.RealmAbilities.AtlasOF_WildHealingAbility','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('262','AtlasOF_WildArcana','Wild Arcana','522','Increases chance to critical with dots and debuffs by the listed percentage.','0','DOL.GS.RealmAbilities.AtlasOF_WildArcanaAbility','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('263','AtlasOF_AoM','Avoidance of Magic','523','Reduces all magic damage taken by the listed percentage.','0','DOL.GS.RealmAbilities.AtlasOF_AvoidanceOfMagicAbility','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('264','AtlasOF_Determination','Determination','524','Reduces the duration of all crowd control spells by the listed percentage. Effect is cumulative at each level increase.','0','DOL.GS.RealmAbilities.AtlasOF_DeterminationAbility','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('265','AtlasOF_FalconsEye','Falcon\'s Eye','525','Increases the chance of dealing a critical hit with archery by the listed percentage amount.','0','DOL.GS.RealmAbilities.AtlasOF_FalconsEye','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('266','AtlasOF_Dodger','Dodger','526','Increases chance to evade by the listed percentage amount.','0','DOL.GS.RealmAbilities.AtlasOF_Dodger','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('267','AtlasOF_Serenity','Serenity','527','Adds to the amount of power regenerated over time.','0','DOL.GS.RealmAbilities.AtlasOF_SerenityAbility','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('268','AtlasOF_EtherealBond','Ethereal Bond (Atlas OF)','528','Increases maximum power by 3% per level of this ability. Requires Serenity 2.','0','DOL.GS.RealmAbilities.AtlasOF_EtherealBondAbility','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('269','AtlasOF_Lifter','Lifter (Atlas OF)','529','20% additional maximum carrying capacity per level.','0','DOL.GS.RealmAbilities.AtlasOF_LifterAbility','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('270','AtlasOF_Toughness','Toughness (Atlas OF)','530','Increases maximum hit points by 3% per level of this ability.','0','DOL.GS.RealmAbilities.AtlasOF_ToughnessAbility','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('271','AtlasOF_Regeneration','Regeneration','531','Your hit points regenerate faster than normal.','0','DOL.GS.RealmAbilities.AtlasOF_Regeneration','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('272','AtlasOF_VeilRecovery','Veil Recovery','532','Reduces duration of resurrection sickness by 10% per level.','0','DOL.GS.RealmAbilities.AtlasOF_VeilRecovery','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('273','AtlasOF_MasteryOfStealth','Mastery of Stealth','533','Grants 5% movement speed increase while stealthed per level of this ability.','0','DOL.GS.RealmAbilities.AtlasOF_MasteryOfStealth','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('274','AtlasOF_ArrowSalvaging','Arrow Salvaging','534','10% chance per level to not expend arrow on firing.','0','DOL.GS.RealmAbilities.AtlasOF_ArrowSalvaging','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('275','AtlasOF_DualistsReflexes','Dualist\'s Reflexes','535','Additional 3% dual wield chance/damage for dual wield/left axe users per level of this ability.','0','DOL.GS.RealmAbilities.AtlasOF_DualistsReflexes','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('276','AtlasOF_SeeHidden','See Hidden','536','Automatically detect stealthed characters that don\'t have the \"SeeHidden\" ability: Scouts, Hunters, Rangers, and Minstrels.','0','DOL.GS.RealmAbilities.AtlasOF_SeeHidden','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('277','AtlasOF_FirstAid','First Aid','537','Self heal that heals approximately 30% hit points per level gained in the ability. It cannot be used in combat.','0','DOL.GS.RealmAbilities.AtlasOF_FirstAid','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('278','AtlasOF_Trip','Trip','538','Point-blank radius snare that reduces the movement of all enemies in the area by 30% for 12 seconds.','0','DOL.GS.RealmAbilities.AtlasOF_Trip','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('279','AtlasOF_Grapple','Grapple','539','Point-blank radius root that immobilizes the movement of all enemies in the area for 12 seconds. Requires Trip.','0','DOL.GS.RealmAbilities.AtlasOF_Grapple','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('280','AtlasOF_AvoidPain','Avoid Pain','540','60 second boost to physical damage absorption, 10% per level per level of this ability.','0','DOL.GS.RealmAbilities.AtlasOF_AvoidPain','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('281','AtlasOF_ArmorOfFaith','Armor of Faith','541','60 second, 50 boost to armor factor per level of this ability.','0','DOL.GS.RealmAbilities.AtlasOF_ArmorOfFaith','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('282','AtlasOF_WhirlingDervish','Whirling Dervish','542','60 second 5% boost to dual wield chance/left axe damage per level of this ability.','0','DOL.GS.RealmAbilities.AtlasOF_WhirlingDervish','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('283','AtlasOF_Bladedance','Bladedance ','543','Point-blank radius direct damage attack that damages all enemies in the spell area.','0','DOL.GS.RealmAbilities.AtlasOF_Bladedance','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('284','AtlasOF_HailOfBlows','Hail of Blows ','544','5% per level boosted attack speed for 60 seconds. This ability is currently affected by the haste cap, and thus has less benefit on faster weapons.','0','DOL.GS.RealmAbilities.AtlasOF_HailOfBlows','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('285','AtlasOF_SecondWind','Second Wind','545','Completely restores your character’s endurance.','0','DOL.GS.RealmAbilities.AtlasOF_SecondWind','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('286','AtlasOF_BattleYell','Battle Yell','546','Point-blank radius taunt; does no damage but draws monster aggression for all enemy monsters in affected area.','0','DOL.GS.RealmAbilities.AtlasOF_BattleYell','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('287','AtlasOF_IgnorePain','IgnorePain','547','Self heal that heals approximately 20% hit points per level, and can be used in combat.','0','DOL.GS.RealmAbilities.AtlasOF_IgnorePain','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('288','AtlasOF_RainOfFire','Rain of Fire','548','Adds a 10% per level heat damage-add to non-magical attacks.','0','DOL.GS.RealmAbilities.AtlasOF_RainOfFire','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('289','AtlasOF_RainOfIce','Rain of Ice','549','Adds a 10% per level cold damage-add to non-magical attacks.','0','DOL.GS.RealmAbilities.AtlasOF_RainOfIce','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('290','AtlasOF_RainOfAnnihilation','Rain of Annihilation','550','Adds a 10% per level spirit damage-add to non-magical attacks.','0','DOL.GS.RealmAbilities.AtlasOF_RainOfAnnihilation','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('291','AtlasOF_Longshot','Longshot','551','A bow shot with no damage bonus that can be fired up to 150% of normal maximum bow range.','0','DOL.GS.RealmAbilities.AtlasOF_Longshot','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('292','AtlasOF_Volley','Volley','552','Ground-targeted archery attack that fires successive arrows at a various targets in a given area. To use this ability, choose a ground target. This target must be at least 66% of your bow\'s normal max range away from you. Use the button. Once you are ready to fire, you can fire up to 5 arrows by hitting your bow button in succession.','437','DOL.GS.RealmAbilities.AtlasOF_Volley','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('293','AtlasOF_Concentration','Concentration','553','Resets quickcast timer to allow for a second quickcast.','0','DOL.GS.RealmAbilities.AtlasOF_Concentration','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('294','AtlasOF_MasteryOfConcentration','Mastery of Concentration','554','Reduces chance of interruption by 100% for 15 seconds. Note that this ability is affected by the level of your attacker.','3006','DOL.GS.RealmAbilities.AtlasOF_MasteryOfConcentration','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('295','AtlasOF_EmptyMind','The Empty Mind','555','10% per level boost to all magic resistances for 60 seconds.','3007','DOL.GS.RealmAbilities.AtlasOF_EmptyMind','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('296','AtlasOF_MajesticWill','Majestic Will','556','Your target’s chance of resisting your spells is reduced by 5% per level per level of this ability for 60 seconds.','0','DOL.GS.RealmAbilities.AtlasOF_MajesticWill','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('297','AtlasOF_RagingPower','Raging Power','557','Full power heal, usable in combat.','3009','DOL.GS.RealmAbilities.AtlasOF_RagingPower','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('298','AtlasOF_ReflexAttack','Reflex Attack','558','For 30 seconds, you will automatically counter-attack any melee attack immediately, with no timer. There is no limit to the number of attackers you can potentially Reflex Attack – any player or monster who attacks you will receive an immedate counter attack.','3011','DOL.GS.RealmAbilities.AtlasOF_ReflexAttack','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('299','AtlasOF_Viper','Viper','559','For 30 seconds, all of your DoT poisons will do double damage.','3012','DOL.GS.RealmAbilities.AtlasOF_Viper','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('300','AtlasOF_TrueSight','True Sight','560','Detect all hidden characters for 60 seconds.','0','DOL.GS.RealmAbilities.AtlasOF_TrueSight','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('301','AtlasOF_SoldiersBarricade','Soldier\'s Barricade','561','Large bonus to group\'s armor factor for 30 seconds.','3014','DOL.GS.RealmAbilities.AtlasOF_SoldiersBarricade','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('302','AtlasOF_BunkerOfFaith','Bunker of Faith','562','30 seconds of 50% bonus to group\'s melee absorption, which means your group will be able to absorb much more damage than normal.','3015','DOL.GS.RealmAbilities.AtlasOF_BunkerOfFaith','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('303','AtlasOF_SiegeBolt','Siege Bolt','563','A targeted bolt spell that does approximately 10 min. points of damage against siege equipment and keep doors.','0','DOL.GS.RealmAbilities.AtlasOF_SiegeBolt','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('304','AtlasOF_FaithHealing','Faith Healing','564','A powerful group heal. This percent-based heal is effectively the same as the highest spec group insta-heals that primary healers get.','0','DOL.GS.RealmAbilities.AtlasOF_FaithHealing','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('305','AtlasOF_WhipOfEncouragement','Whip of Encouragement','565','Your pet moves at twice normal speed for 60 seconds.','0','DOL.GS.RealmAbilities.AtlasOF_WhipOfEncouragement','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('306','AtlasOF_ExcitedFrenzy','Excited Frenzy','566','Your pet attacks at 50% faster than normal for 30 seconds.','0','DOL.GS.RealmAbilities.AtlasOF_ExcitedFrenzy','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('307','AtlasOF_GroupPurge','Group Purge','567','All negative effects (DOTs, poisons, mesmerization, stun, rez sickness, etc.) are purged from all group members.','0','DOL.GS.RealmAbilities.AtlasOF_GroupPurge','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('308','AtlasOF_PerfectRecovery','Perfect Recovery','568','After death, you will resurrect with full hitpoints and power and no resurrection side-effects.','3018','DOL.GS.RealmAbilities.AtlasOF_PerfectRecovery','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('309','AtlasOF_Vanish','Vanish','569','You will immediately hide, regardless of action state or in-combat timer.','3019','DOL.GS.RealmAbilities.AtlasOF_Vanish','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('310','AtlasOF_ShadowRun','Shadow Run','570','Your run speed while steathed is boosted for 30 seconds.','0','DOL.GS.RealmAbilities.AtlasOF_ShadowRun','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('311','AtlasOF_SpeedOfSound','Speed of Sound','571','Your group moves at twice normal speed for 30 seconds. This ability will not break in combat. This ability also bypasses the movement penalties from mesmerize, root/snare, and stun, although other  effects such as inability to attack will remain.','3020','DOL.GS.RealmAbilities.AtlasOF_SpeedOfSound','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('312','AtlasOF_AmelioratingMelodies','Ameliorating Melodies','572','Your group will receive a massive health regeneration boost for 30 seconds.','3021','DOL.GS.RealmAbilities.AtlasOF_AmelioratingMelodies','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('313','AtlasOF_FuryOfTheGods','Fury of the Gods','573','A group damage-add spell that lasts for 30 seconds and stacks on top of other damage-add effects. This ability is percent-based, so its damage goes up with the user\'s level. Does not stack with Triple Wield or Rain of Fire/Ice/Annihilation.','0','DOL.GS.RealmAbilities.AtlasOF_FuryOfTheGods','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('314','AtlasOF_WrathOfTheChampion','Wrath of the Champion','574','Point-blank radius direct damage that immediately damages all enemeis in area of effect. This ability is percent-based, so its damage goes up with the user\'s level.','3023','DOL.GS.RealmAbilities.AtlasOF_WrathOfTheChampion','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('315','AtlasOF_VolcanicPillar','Volcanic Pillar','575','High damage radius direct damage spell that immediately damages all enemies in area of effect. This ability is percent-based, so its damage goes up with the user\'s level.','3024','DOL.GS.RealmAbilities.AtlasOF_VolcanicPillar','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('316','AtlasOF_RuneOfDecimation','Rune of Decimation','576','Trap that damages any opponents nearby when they approach. Casts at casters feet. Every few seconds the trap looks for a target in its area. When it finds one, it triggers the radius direct damage spell on that target, which will damage the target as well as all other enemies in its area of effect. The trap will stay on the ground for 8 minutes before it disappears.','3025','DOL.GS.RealmAbilities.AtlasOF_RuneOfDecimation','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('317','AtlasOF_NegativeMaelstrom','Negative Maelstrom','577','Ground-targetted radius cloud spell that lasts 30 seconds. Every 3 seconds anyone within the radius of the object representing the center of the cloud takes damage. The damage is percent based, and goes up with the user\'s level.','3026','DOL.GS.RealmAbilities.AtlasOF_NegativeMaelstrom','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('318','AtlasOF_ThornweedField','Thornweed Field','578','Ground-targetted cloud spell that lasts 30 seconds. Every 5 seconds, anyone within radius of the object representing the center of the cloud  takes damage and is 35% snared. The damage is percent based, and goes up with the user\'s level.','3027','DOL.GS.RealmAbilities.AtlasOF_ThornweedField','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('319','AtlasOF_CorporealDisintegration','Corporeal Distintegration','579','Radius DoT spell, stacks with other DOT lines. Damage is percent based, and goes up with the user\'s level.','0','DOL.GS.RealmAbilities.AtlasOF_CorporealDisintegration','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('320','AtlasOF_Ichor','Ichor Of The Deep','580','Radius direct damage plus root, which means that any enemy in the spell’s area is damaged and rooted.','3028','DOL.GS.RealmAbilities.AtlasOF_Ichor','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('321','AtlasOF_BrilliantAura','Brilliant Aura Of Deflection','581','Your character receives a 30 second boost to all magical resistances.','3029','DOL.GS.RealmAbilities.AtlasOF_BrilliantAura','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('322','AtlasOF_SeveringTheTether','Severing The Tether','582','All enemy summoned/controlled creatures (i.e. pets) in the spell’s radius immediately turn on their masters and attack them. This is a ground-targetted radius effect spell.','0','DOL.GS.RealmAbilities.AtlasOF_SeveringTheTether','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('323','AtlasOF_Juggernaut','Juggernaut','583','Summons a pet of your level (i.e. a “100%” pet) that lasts for 4 minutes.','3030','DOL.GS.RealmAbilities.AtlasOF_Juggernaut','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('324','AtlasOF_StaticTempest','Static Tempest','584','Ground-targetted radius cloud spell that lasts 30 seconds. Every 7 seconds anyone near the object representing the center of the cloud is stunned for 3 seconds.','3031','DOL.GS.RealmAbilities.AtlasOF_StaticTempest','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('325','AtlasOF_StyleVoid','Style: Void','585','Combat Style: Opening: None Weapon type: Any Fatigue cost: None Damage: Very high Attack  Bonus: Very high Defense bonus: Medium','0','DOL.GS.RealmAbilities.AtlasOF_StyleVoid','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('326','AtlasOF_StyleDoombringer','Style: Doombringer','586','Combat Style: Opening: None Weapon type: Any Fatigue cost: None Damage: Very high Attack  bonus: Very high Defense bonus: Medium','0','DOL.GS.RealmAbilities.AtlasOF_StyleDoombringer','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('327','AtlasOF_StyleTundra','Style: Tundra','587','Combat Style: Opening: None Weapon type: Any Fatigue cost: None Damage: Very high Attack bonus: Very high Defense bonus: Medium Note: Using Tundra and Left Axe at the same time will greatly reduce the damage of the style.','0','DOL.GS.RealmAbilities.AtlasOF_StyleTundra','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('328','AtlasOF_StyleWinterMoon','Style: Winter Moon','588','Combat Style: Opening: None Weapon type: Any Fatigue cost: None Damage: Very high Attack bonus: Very high Defense bonus: Medium','0','DOL.GS.RealmAbilities.AtlasOF_StyleWinterMoon','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('329','AtlasOF_StyleRazorback','Style: Razorback','589','Combat Style: Opening: None Weapon type: Any Fatigue cost: None Damage: Very high Attack  Bonus: Very high Defense bonus: Medium','0','DOL.GS.RealmAbilities.AtlasOF_StyleRazorback','2000-01-01 00:00:00');
        INSERT INTO ability (AbilityID,KeyName,Name,InternalID,Description,IconID,Implementation,LastTimeRowUpdated) VALUES ('330','AtlasOF_PreventFlight','Prevent Flight','590','If the tank\'s selected target turns and runs, the tank has a 35% chance of hitting and proccing a 50% snare for 10 seconds.','0','DOL.GS.RealmAbilities.AtlasOF_PreventFlight','2000-01-01 00:00:00');


        -- ADD REALM ABILITES WITH FOREIGN KEY FROM TABLE : ability
        -- MINSTREL --
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_AugAcuity', '2000-01-01 00:00:00', 'Minstrel1-0-1');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_AugCon', '2000-01-01 00:00:00', 'Minstrel1-0-2');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_AugDex', '2000-01-01 00:00:00', 'Minstrel1-0-3');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_AugQui', '2000-01-01 00:00:00', 'Minstrel1-0-4');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_AugStr', '2000-01-01 00:00:00', 'Minstrel1-0-5');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_MCL', '2000-01-01 00:00:00', 'Minstrel1-0-6');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_Purge', '2000-01-01 00:00:00', 'Minstrel1-0-7');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_LongWind', '2000-01-01 00:00:00', 'Minstrel1-0-8');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_MasteryOfPain', '2000-01-01 00:00:00', 'Minstrel1-0-9');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_MasteryOfParrying', '2000-01-01 00:00:00', 'Minstrel1-1-0');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_MasteryOfBlocking', '2000-01-01 00:00:00', 'Minstrel1-1-1');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_MasteryOfArms', '2000-01-01 00:00:00', 'Minstrel1-1-2');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_MasteryOfMagery', '2000-01-01 00:00:00', 'Minstrel1-1-3');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_MasteryOfArchery', '2000-01-01 00:00:00', 'Minstrel1-1-4');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_MasteryOfWater', '2000-01-01 00:00:00', 'Minstrel1-1-5');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_MasteryOfTheArt', '2000-01-01 00:00:00', 'Minstrel1-1-6');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_MasteryOfTheArcane', '2000-01-01 00:00:00', 'Minstrel1-1-7');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_MasteryOfHealing', '2000-01-01 00:00:00', 'Minstrel1-1-8');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_AoM', '2000-01-01 00:00:00', 'Minstrel1-1-9');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_Dodger', '2000-01-01 00:00:00', 'Minstrel1-2-0');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_Serenity', '2000-01-01 00:00:00', 'Minstrel1-2-1');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_EtherealBond', '2000-01-01 00:00:00', 'Minstrel1-2-2');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_Lifter', '2000-01-01 00:00:00', 'Minstrel1-2-3');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (4, 'AtlasOF_Toughness', '2000-01-01 00:00:00', 'Minstrel1-2-4');

        -- SORCERER --
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (8, 'AtlasOF_MasteryOfTheArt', '2000-01-01 00:00:00', 'Sorcerer1-0-3');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (8, 'AtlasOF_AugAcuity', '2000-01-01 00:00:00', 'Sorcerer1-0-4');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (8, 'AtlasOF_AugDex', '2000-01-01 00:00:00', 'Sorcerer1-0-5');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (8, 'AtlasOF_MasteryOfMagery', '2000-01-01 00:00:00', 'Sorcerer1-0-6');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (8, 'AtlasOF_WildPower', '2000-01-01 00:00:00', 'Sorcerer1-0-7');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (8, 'AtlasOF_WildMinion', '2000-01-01 00:00:00', 'Sorcerer1-0-8');

        -- CABALIST --
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (13, 'AtlasOF_AugAcuity', '2000-01-01 00:00:00', 'Cabalist1-0-1');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (13, 'AtlasOF_WildMinion', '2000-01-01 00:00:00', 'Cabalist1-0-2');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (13, 'AtlasOF_WildArcana', '2000-01-01 00:00:00', 'Cabalist1-0-3');

        -- FRIAR --
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (10, 'AtlasOF_AugAcuity', '2000-01-01 00:00:00', 'Friar1-0-1');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (10, 'AtlasOF_AugDex', '2000-01-01 00:00:00', 'Friar1-0-2');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (10, 'AtlasOF_WildHealing', '2000-01-01 00:00:00', 'Friar1-0-3');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (10, 'AtlasOF_MasteryOfParrying', '2000-01-01 00:00:00', 'Friar1-1-4');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (10, 'AtlasOF_MasteryOfTheArcane', '2000-01-01 00:00:00', 'Friar1-0-5');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (10, 'AtlasOF_Determination', '2000-01-01 00:00:00', 'Friar1-0-6');

        -- SCOUT --
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (3, 'AtlasOF_AugDex', '2000-01-01 00:00:00', 'Scout1-0-1');
        INSERT INTO `classxrealmability_atlas` (`CharClass`, `AbilityKey`, `LastTimeRowUpdated`, `ClassXRealmAbility_Atlas_ID`) VALUES (3, 'AtlasOF_FalconsEye', '2000-01-01 00:00:00', 'Scout1-0-2');

        */
    }
}
