namespace Core.GS;

public enum ERace : byte
{
	Unknown = 0,
	Briton = 1,
	Avalonian = 2,
	Highlander = 3,
	Saracen = 4,
	Norseman = 5,
	Troll = 6,
	Dwarf = 7,
	Kobold = 8,
	Celt = 9,
	Firbolg = 10,
	Elf = 11,
	Lurikeen = 12,
	Inconnu = 13,
	Valkyn = 14,
	Sylvan = 15,
	HalfOgre = 16,
	Frostalf = 17,
	Shar = 18,
	AlbionMinotaur = 19,
	MidgardMinotaur = 20,
	HiberniaMinotaur = 21,
	Korazh = 19,
	Deifrang = 20,
	Graoch = 21,
}