/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE TABLE IF NOT EXISTS `accountxmoney` (
  `AccountId` varchar(255) NOT NULL,
  `Realm` int(11) NOT NULL DEFAULT 0,
  `Copper` int(11) NOT NULL DEFAULT 0,
  `Silver` int(11) NOT NULL DEFAULT 0,
  `Gold` int(11) NOT NULL DEFAULT 0,
  `Platinum` int(11) NOT NULL DEFAULT 0,
  `Mithril` int(11) NOT NULL DEFAULT 0,
  `AccountxMoney_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LastTimeRowUpdated` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  PRIMARY KEY (`AccountxMoney_ID`),
  KEY `I_AccountXMoney_AccountId` (`AccountId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

/*!40000 ALTER TABLE `accountxmoney` DISABLE KEYS */;
/*!40000 ALTER TABLE `accountxmoney` ENABLE KEYS */;

