/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE TABLE IF NOT EXISTS `ban` (
  `Author` text NOT NULL,
  `Type` varchar(255) NOT NULL,
  `Ip` varchar(255) NOT NULL,
  `Account` varchar(255) NOT NULL,
  `DateBan` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `Reason` text NOT NULL,
  `LastTimeRowUpdated` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `Ban_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`Ban_ID`),
  KEY `I_Ban_Type` (`Type`),
  KEY `I_Ban_Ip` (`Ip`),
  KEY `I_Ban_Account` (`Account`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

/*!40000 ALTER TABLE `ban` DISABLE KEYS */;
/*!40000 ALTER TABLE `ban` ENABLE KEYS */;

