/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE TABLE IF NOT EXISTS `dboutdooritem` (
  `HouseNumber` int(11) NOT NULL DEFAULT 0,
  `Model` int(11) NOT NULL DEFAULT 0,
  `Position` int(11) NOT NULL DEFAULT 0,
  `Rotation` int(11) NOT NULL DEFAULT 0,
  `BaseItemID` text NOT NULL,
  `LastTimeRowUpdated` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `DBOutdoorItem_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`DBOutdoorItem_ID`),
  KEY `I_DBOutdoorItem_HouseNumber` (`HouseNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

/*!40000 ALTER TABLE `dboutdooritem` DISABLE KEYS */;
/*!40000 ALTER TABLE `dboutdooritem` ENABLE KEYS */;

