/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE TABLE IF NOT EXISTS `dolcharactersbackup` (
  `DOLCharacters_ID` varchar(255) NOT NULL,
  `Name` varchar(255) NOT NULL,
  `DeleteDate` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `HasGravestone` tinyint(1) NOT NULL DEFAULT 0,
  `GravestoneRegion` int(11) NOT NULL DEFAULT 0,
  `Constitution` int(11) NOT NULL DEFAULT 0,
  `Dexterity` int(11) NOT NULL DEFAULT 0,
  `Strength` int(11) NOT NULL DEFAULT 0,
  `Quickness` int(11) NOT NULL DEFAULT 0,
  `Intelligence` int(11) NOT NULL DEFAULT 0,
  `Piety` int(11) NOT NULL DEFAULT 0,
  `Empathy` int(11) NOT NULL DEFAULT 0,
  `Charisma` int(11) NOT NULL DEFAULT 0,
  `BountyPoints` bigint(20) NOT NULL DEFAULT 0,
  `RealmPoints` bigint(20) NOT NULL DEFAULT 0,
  `RealmLevel` int(11) NOT NULL DEFAULT 0,
  `Experience` bigint(20) NOT NULL DEFAULT 0,
  `MaxEndurance` int(11) NOT NULL DEFAULT 0,
  `Health` int(11) NOT NULL DEFAULT 0,
  `Mana` int(11) NOT NULL DEFAULT 0,
  `Endurance` int(11) NOT NULL DEFAULT 0,
  `Concentration` int(11) NOT NULL DEFAULT 0,
  `AccountName` varchar(255) NOT NULL,
  `AccountSlot` int(11) NOT NULL DEFAULT 0,
  `CreationDate` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `LastPlayed` datetime DEFAULT NULL,
  `LastName` text DEFAULT NULL,
  `GuildID` varchar(255) DEFAULT NULL,
  `Gender` int(11) NOT NULL DEFAULT 0,
  `Race` int(11) NOT NULL DEFAULT 0,
  `Level` int(11) NOT NULL DEFAULT 0,
  `Class` int(11) NOT NULL DEFAULT 0,
  `Realm` int(11) NOT NULL DEFAULT 0,
  `CreationModel` int(11) NOT NULL DEFAULT 0,
  `CurrentModel` int(11) NOT NULL DEFAULT 0,
  `Region` int(11) NOT NULL DEFAULT 0,
  `ActiveWeaponSlot` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `Xpos` int(11) NOT NULL DEFAULT 0,
  `Ypos` int(11) NOT NULL DEFAULT 0,
  `Zpos` int(11) NOT NULL DEFAULT 0,
  `BindXpos` int(11) NOT NULL DEFAULT 0,
  `BindYpos` int(11) NOT NULL DEFAULT 0,
  `BindZpos` int(11) NOT NULL DEFAULT 0,
  `BindRegion` int(11) NOT NULL DEFAULT 0,
  `BindHeading` int(11) NOT NULL DEFAULT 0,
  `BindHouseXpos` int(11) NOT NULL DEFAULT 0,
  `BindHouseYpos` int(11) NOT NULL DEFAULT 0,
  `BindHouseZpos` int(11) NOT NULL DEFAULT 0,
  `BindHouseRegion` int(11) NOT NULL DEFAULT 0,
  `BindHouseHeading` int(11) NOT NULL DEFAULT 0,
  `DeathCount` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `ConLostAtDeath` int(11) NOT NULL DEFAULT 0,
  `Direction` int(11) NOT NULL DEFAULT 0,
  `MaxSpeed` int(11) NOT NULL DEFAULT 0,
  `Copper` int(11) NOT NULL DEFAULT 0,
  `Silver` int(11) NOT NULL DEFAULT 0,
  `Gold` int(11) NOT NULL DEFAULT 0,
  `Platinum` int(11) NOT NULL DEFAULT 0,
  `Mithril` int(11) NOT NULL DEFAULT 0,
  `SerializedCraftingSkills` text DEFAULT NULL,
  `SerializedAbilities` text DEFAULT NULL,
  `SerializedSpecs` text DEFAULT NULL,
  `SerializedRealmAbilities` text DEFAULT NULL,
  `DisabledSpells` text DEFAULT NULL,
  `DisabledAbilities` text DEFAULT NULL,
  `SerializedFriendsList` text DEFAULT NULL,
  `SerializedIgnoreList` text DEFAULT NULL,
  `IsCloakHoodUp` tinyint(1) NOT NULL DEFAULT 0,
  `IsCloakInvisible` tinyint(1) NOT NULL DEFAULT 0,
  `IsHelmInvisible` tinyint(1) NOT NULL DEFAULT 0,
  `SpellQueue` tinyint(1) NOT NULL DEFAULT 0,
  `IsLevelSecondStage` tinyint(1) NOT NULL DEFAULT 0,
  `FlagClassName` tinyint(1) NOT NULL DEFAULT 0,
  `Advisor` tinyint(1) NOT NULL DEFAULT 0,
  `GuildRank` smallint(5) unsigned NOT NULL DEFAULT 0,
  `PlayedTime` bigint(20) NOT NULL DEFAULT 0,
  `DeathTime` bigint(20) NOT NULL DEFAULT 0,
  `RespecAmountAllSkill` int(11) NOT NULL DEFAULT 0,
  `RespecAmountSingleSkill` int(11) NOT NULL DEFAULT 0,
  `RespecAmountRealmSkill` int(11) NOT NULL DEFAULT 0,
  `RespecAmountDOL` int(11) NOT NULL DEFAULT 0,
  `RespecAmountChampionSkill` int(11) NOT NULL DEFAULT 0,
  `IsLevelRespecUsed` tinyint(1) NOT NULL DEFAULT 0,
  `RespecBought` int(11) NOT NULL DEFAULT 0,
  `SafetyFlag` tinyint(1) NOT NULL DEFAULT 0,
  `CraftingPrimarySkill` int(11) NOT NULL DEFAULT 0,
  `CancelStyle` tinyint(1) NOT NULL DEFAULT 0,
  `IsAnonymous` tinyint(1) NOT NULL DEFAULT 0,
  `CustomisationStep` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `EyeSize` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `LipSize` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `EyeColor` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `HairColor` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `FaceType` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `HairStyle` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `MoodType` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `UsedLevelCommand` tinyint(1) NOT NULL DEFAULT 0,
  `CurrentTitleType` text DEFAULT NULL,
  `KillsAlbionPlayers` int(11) NOT NULL DEFAULT 0,
  `KillsMidgardPlayers` int(11) NOT NULL DEFAULT 0,
  `KillsHiberniaPlayers` int(11) NOT NULL DEFAULT 0,
  `KillsAlbionDeathBlows` int(11) NOT NULL DEFAULT 0,
  `KillsMidgardDeathBlows` int(11) NOT NULL DEFAULT 0,
  `KillsHiberniaDeathBlows` int(11) NOT NULL DEFAULT 0,
  `KillsAlbionSolo` int(11) NOT NULL DEFAULT 0,
  `KillsMidgardSolo` int(11) NOT NULL DEFAULT 0,
  `KillsHiberniaSolo` int(11) NOT NULL DEFAULT 0,
  `CapturedKeeps` int(11) NOT NULL DEFAULT 0,
  `CapturedTowers` int(11) NOT NULL DEFAULT 0,
  `CapturedRelics` int(11) NOT NULL DEFAULT 0,
  `KillsDragon` int(11) NOT NULL DEFAULT 0,
  `DeathsPvP` int(11) NOT NULL DEFAULT 0,
  `KillsLegion` int(11) NOT NULL DEFAULT 0,
  `KillsEpicBoss` int(11) NOT NULL DEFAULT 0,
  `GainXP` tinyint(1) NOT NULL DEFAULT 0,
  `GainRP` tinyint(1) NOT NULL DEFAULT 0,
  `Autoloot` tinyint(1) NOT NULL DEFAULT 0,
  `LastFreeLeveled` datetime DEFAULT NULL,
  `LastFreeLevel` int(11) NOT NULL DEFAULT 0,
  `GuildNote` text DEFAULT NULL,
  `ShowXFireInfo` tinyint(1) NOT NULL DEFAULT 0,
  `ShowGuildLogins` tinyint(1) NOT NULL DEFAULT 0,
  `Champion` tinyint(1) NOT NULL DEFAULT 0,
  `ChampionLevel` int(11) NOT NULL DEFAULT 0,
  `ChampionExperience` bigint(20) NOT NULL DEFAULT 0,
  `ML` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `MLExperience` bigint(20) NOT NULL DEFAULT 0,
  `MLLevel` int(11) NOT NULL DEFAULT 0,
  `MLGranted` tinyint(1) NOT NULL DEFAULT 0,
  `RPFlag` tinyint(1) NOT NULL DEFAULT 0,
  `IgnoreStatistics` tinyint(1) NOT NULL DEFAULT 0,
  `NotDisplayedInHerald` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `ActiveSaddleBags` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `LastTimeRowUpdated` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `DOLCharactersBackup_ID` varchar(255) NOT NULL,
  `LastLevelUp` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `PlayedTimeSinceLevel` bigint(20) NOT NULL DEFAULT 0,
  `HCFlag` tinyint(1) NOT NULL DEFAULT 0,
  `HCCompleted` tinyint(1) NOT NULL DEFAULT 0,
  `HideSpecializationAPI` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`DOLCharactersBackup_ID`),
  KEY `I_DOLCharactersBackup_Name` (`Name`),
  KEY `I_DOLCharactersBackup_AccountName` (`AccountName`),
  KEY `I_DOLCharactersBackup_GuildID` (`GuildID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

/*!40000 ALTER TABLE `dolcharactersbackup` DISABLE KEYS */;
/*!40000 ALTER TABLE `dolcharactersbackup` ENABLE KEYS */;

