/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE TABLE IF NOT EXISTS `mobxambientbehaviour` (
  `Source` varchar(255) NOT NULL,
  `Trigger` text NOT NULL,
  `Emote` smallint(5) unsigned NOT NULL DEFAULT 0,
  `Text` text NOT NULL,
  `Chance` smallint(5) unsigned NOT NULL DEFAULT 0,
  `Voice` text DEFAULT NULL,
  `LastTimeRowUpdated` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `MobXAmbientBehaviour_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`MobXAmbientBehaviour_ID`),
  KEY `I_MobXAmbientBehaviour_Source` (`Source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

/*!40000 ALTER TABLE `mobxambientbehaviour` DISABLE KEYS */;
REPLACE INTO `mobxambientbehaviour` (`Source`, `Trigger`, `Emote`, `Text`, `Chance`, `Voice`, `LastTimeRowUpdated`, `MobXAmbientBehaviour_ID`) VALUES
	('Korban', 'aggroing', 0, 'The blood of the Seithkona runs true in my veins fool!', 100, '', '2022-05-06 20:16:33', '02343e58-d1ae-4dd5-a7d6-df890aab3886'),
	('Fusi', 'roaming', 0, '{sourcename} says, "Meooow!"', 75, 'c', '2021-10-20 13:17:42', '297bf94d-2287-4740-bf88-e258970f63dc'),
	('Fusi', 'interact', 0, '{sourcename} says, "Purr Purrrrr!"', 100, 'c', '2021-10-20 13:53:45', '380fa5a8-6276-422a-aa5b-609072bd0b4f'),
	('Atlas', 'interact', 5, '{sourcename} says, "Thank you for playing Atlas and for your contribution in our tests."', 25, 'c', '2021-11-20 17:14:56', '49db8682-7d42-4b0b-94a8-7262a3cd06d8'),
	('Fusi', 'interact', 0, '{sourcename} says, "Purr Purrrrrrrr!"', 100, 'c', '2021-10-20 13:16:53', '555e3b8a-98b6-4343-ac8e-7c316dc854f6'),
	('Atlas', 'interact', 40, '{sourcename} says, "{targetname}, you finished your {class} training? Then equip yourself and find a group to fight the enemies! I heard the Event Teleporter will send you to Grenlock. Be Careful, for Atlas!"', 25, 'c', '2021-11-21 00:09:32', '7b8ef870-accb-4a44-abed-56d217b67597'),
	('Fusi', 'roaming', 0, '{sourcename} says, "Meoow, Meeooooww!"', 50, 'c', '2021-10-20 13:53:38', '8b003064-09c7-4d38-9b4f-431a0444ce60'),
	('Fusi', 'roaming', 0, '{sourcename} says, "Meoow Meoooooow!"', 50, 'c', '2021-10-20 15:05:34', '902bc172-d701-4fdf-8432-42a55adede5e'),
	('Fusi', 'roaming', 0, '{sourcename} says, "Meooow!"', 50, 'c', '2021-10-20 13:53:36', '9a935a17-9cc8-463c-8f5a-40ad47ad5de2'),
	('Atlas', 'interact', 9, '{sourcename} says, "Hi {targetname}, if you have any suggestions, feel free to create a topic in our forum. Thank you!"', 25, 'c', '2021-11-21 00:12:03', '9ea895b7-fd48-4e38-9d96-b7a9ae447aef'),
	('Fusi', 'roaming', 0, '{sourcename} says, "Meooow!"', 50, 'c', '2021-10-20 13:50:22', 'a4a294e9-5ae4-4d28-9144-759efe77cd1a'),
	('Alden Fletcher', 'interact', 0, '{sourcename} says, "So, you want to buy something eh? Well here is what I have."', 100, 'c', '2021-12-28 12:33:43', 'alb-alden-greeting-hereswhatihave'),
	('Armsman Commander', 'aggroing', 0, '{sourcename} says, "We\'re under attack! Defend your land!"', 100, 'c', '2021-12-28 12:40:47', 'alb-armsmancomm-aggro-defendland'),
	('Armswoman Commander', 'aggroing', 0, '{sourcename} says, "We\'re under attack! Defend your land!"', 100, 'c', '2021-12-28 12:40:47', 'alb-armswomancomm-aggro-defendland'),
	('Col Aldar', 'interact', 0, '{sourcename} says, "So, you want to buy something eh? Well here is what I have."', 100, 'c', '2022-01-22 15:00:00', 'alb-colaldar-greeting-hereiswhatihave'),
	('Corporal Dunleigh', 'aggroing', 0, '{sourcename} says, "For the Glory of Camelot!', 100, 'c', '2021-12-28 12:40:47', 'alb-corporaldunleigh-aggro-glorycamelot'),
	('cutpurse', 'aggroing', 0, '{sourcename} says, "Your money or your life! Aha! I know. I\'ll take both!"', 50, 'c', '2021-12-28 12:40:47', 'alb-cutpurse-aggro-moneyorlife'),
	('cutpurse', 'fighting', 0, '{sourcename} says, "Rob from the rich... that\'s my motto... Give it up!"', 3, 'c', '2021-12-28 12:40:47', 'alb-cutpurse-fighting-robfromrich'),
	('decayed zombie', 'aggroing', 0, '{sourcename} says, "Brains! I want brains!', 30, 'c', '2021-12-28 12:40:47', 'alb-decayzombie-aggro-brains'),
	('Ellyn Weyland', 'interact', 0, '{sourcename} says, "So, you want to buy something eh? Well here is what I have."', 100, 'c', '2021-12-28 12:33:43', 'alb-ellyn-greeting-hereswhatihave'),
	('Fellya Fletcher', 'interact', 0, '{sourcename} says, "So, you want to buy something eh? Well here is what I have."', 100, 'c', '2021-12-28 12:33:43', 'alb-fellya-greeting-hereswhatihave'),
	('Guard Dafydd', 'aggroing', 0, '{sourcename} says, "For the Glory of Camelot!"', 100, 'c', '2021-12-28 12:40:47', 'alb-guarddafydd-aggro-glorycamelot'),
	('Guard Eiddef', 'aggroing', 0, '{sourcename} says, "For the Glory of Camelot!"', 100, 'c', '2021-12-28 12:40:47', 'alb-guardeiddef-aggro-glorycamelot'),
	('Guardsman', 'aggroing', 0, '{sourcename} says, "Have at thee, fiend!"', 100, 'c', '2021-12-28 12:40:47', 'alb-guardsman-aggro-haveatthee'),
	('Guy Reed', 'seeing', 0, '{sourcename} says, "Wonderful, Yasminea! Wonderful!"', 20, 'c', '2021-12-28 12:40:47', 'alb-guyreed-seeing-wonderful'),
	('Keenar Woedin', 'seeing', 0, '{sourcename} says, "Excellent, Yasminea! Show us some more tricks!"', 20, 'c', '2021-12-28 12:40:47', 'alb-keenarwoedin-seeing-wonderful'),
	('keltoi initiate', 'dying', 0, '{sourcename} says, "Never grieve over the irretrievable."', 50, 'c', '2021-12-28 12:40:47', 'alb-keltoiinitiate-dying-irretrievable'),
	('Knight Commander', 'aggroing', 0, '{sourcename} says, "We\'re under attack! Defend your land!"', 100, 'c', '2021-12-28 12:40:47', 'alb-knightcomm-aggro-defendland'),
	('Lady Aelawen', 'aggroing', 0, '{sourcename} says, "For the Glory of Camelot!', 100, 'c', '2021-12-28 12:40:47', 'alb-ladyaelawen-aggro-glorycamelot'),
	('Lord Caddug', 'dying', 0, '{sourcename} says, "Your victory will be short-lived, fiends. By my dying breath I swear, you will not hold Caer Caddug for long, even if I have to haunt this place until the end of days!"', 100, 'c', '2021-12-28 12:40:47', 'alb-lordcaddug-dying-hauntthisplace'),
	('Master Wizard', 'aggroing', 0, '{sourcename} says, "Have at them! Let your spells drive to their very hearts!"', 100, 'c', '2021-12-28 12:38:14', 'alb-masterwizard-aggro-haveatthem'),
	('Pebble', 'seeing', 20, 'Pebble dances!', 30, 'c', '2021-12-28 12:40:47', 'alb-pebble-seeing-dance'),
	('Rayn Olwyc', 'interact', 0, '{sourcename} says, "So, you want to buy something eh? Well here is what I have."', 100, 'c', '2022-01-22 15:00:00', 'alb-raynolwyc-greeting-hereiswhatihave'),
	('Ris\'nir Cruss', 'aggroing', 0, '{sourcename} says, "Fools! You will soon join my army of undead! Hahaha!"', 100, 'c', '2021-12-28 12:40:47', 'alb-risnircruss-aggro-fools'),
	('Salisbury giant', 'aggroing', 0, '{sourcename} says, "I will pound you into the ground!"', 50, 'c', '2021-12-28 12:40:47', 'alb-salisburygiant-aggro-poundyou'),
	('scrawny bogman', 'roaming', 0, '{sourcename} says, "Arthur make us leave before. Arthur dead. We come back. Our home."', 20, 'c', '2022-01-22 15:00:00', 'alb-scrawnybogman-seeing-arthurdead'),
	('Sergeant Alain', 'aggroing', 0, '{sourcename} says, "For the Glory of Camelot!', 100, 'c', '2021-12-28 12:40:47', 'alb-sergeantalain-aggro-glorycamelot'),
	('Sergeant Grum', 'aggroing', 0, '{sourcename} says, "For the Glory of Camelot!', 100, 'c', '2021-12-28 12:40:47', 'alb-sergeantgrum-aggro-glorycamelot'),
	('Sir Barcroft', 'aggroing', 0, '{sourcename} says, "For the Glory of Camelot!', 100, 'c', '2021-12-28 12:40:47', 'alb-sirbarcroft-aggro-glorycamelot'),
	('Sir Quait', 'aggroing', 0, '{sourcename} says, "For the Glory of Camelot!', 100, 'c', '2021-12-28 12:40:47', 'alb-sirquait-aggro-glorycamelot'),
	('Trini Piper', 'seeing', 0, '{sourcename} says, "Shh... Just watch the show and don\'t make a lot of noise!"', 30, 'c', '2021-12-28 12:40:47', 'alb-trinipiper-seeing-shh'),
	('Veteran Guardsman', 'aggroing', 0, '{sourcename} says, "Have at thee, fiend!"', 100, 'c', '2021-12-28 12:40:47', 'alb-vetguardsman-aggro-haveatthee'),
	('wood ogre mystic', 'aggroing', 0, '{sourcename} says, "Har har har! Time to die puny creature! I will crack your bones and suck your marrow!"', 50, 'c', '2021-12-28 12:40:47', 'alb-woodogremystic-aggro-harharhar'),
	('wood ogre mystic', 'dying', 0, '{sourcename} says, "Arrgh! Great Mother help me, I\'m dying. Curse you!"', 25, 'c', '2021-12-28 12:40:47', 'alb-woodogremystic-dying-greatmother'),
	('Yasminea Darden', 'seeing', 0, '{sourcename} says, "Everyone, watch closely! Even Pebble can do some tricks!"', 50, 'c', '2021-12-28 12:40:47', 'alb-yasminea-seeing-watchclosely'),
	('annoying lucradan', 'roaming', 0, '{sourcename} says, "Nya, nya. Ha ha ha! He he he!"', 50, 'c', '2022-01-22 15:00:00', 'annoyinglucradan-seeing-nyanyahaha'),
	('Fusi', 'roaming', 0, '{sourcename} says, "Meow, Meooow!"', 15, 'c', '2021-10-20 13:15:33', 'b087ce65-0f38-4d59-94de-61e02ef2a383'),
	('balorian ansgar', 'dying', 0, '{sourcename} says, "Lord Balor, I have failed you!"', 20, 'c', '2022-01-22 15:00:00', 'balorianansgar-dying-balorfailedyou'),
	('balorian aonghus', 'dying', 0, '{sourcename} says, "Lord Balor, I have failed you!"', 20, 'c', '2022-01-22 15:00:00', 'balorianaonghus-dying-balorfailedyou'),
	('balorian batair', 'dying', 0, '{sourcename} says, "Lord Balor, I have failed you!"', 20, 'c', '2022-01-22 15:00:00', 'balorianbatair-dying-balorfailedyou'),
	('balorian conall', 'dying', 0, '{sourcename} says, "Lord Balor, I have failed you!"', 20, 'c', '2022-01-22 15:00:00', 'balorianconall-dying-balorfailedyou'),
	('balorian conlaoch', 'dying', 0, '{sourcename} says, "Lord Balor, I have failed you!"', 20, 'c', '2022-01-22 15:00:00', 'balorianconlaoch-dying-balorfailedyou'),
	('balorian diolmhain', 'dying', 0, '{sourcename} says, "Lord Balor, I have failed you!"', 20, 'c', '2022-01-22 15:00:00', 'baloriandiolmhain-dying-balorfailedyou'),
	('balorian donogh', 'dying', 0, '{sourcename} says, "Lord Balor, I have failed you!"', 20, 'c', '2022-01-22 15:00:00', 'baloriandonogh-dying-balorfailedyou'),
	('balorian einion', 'dying', 0, '{sourcename} says, "Lord Balor, I have failed you!"', 20, 'c', '2022-01-22 15:00:00', 'balorianeinion-dying-balorfailedyou'),
	('balorian ewyn', 'dying', 0, '{sourcename} says, "Lord Balor, I have failed you!"', 20, 'c', '2022-01-22 15:00:00', 'balorianewyn-dying-balorfailedyou'),
	('balorian huon', 'dying', 0, '{sourcename} says, "Lord Balor, I have failed you!"', 20, 'c', '2022-01-22 15:00:00', 'balorianhuon-dying-balorfailedyou'),
	('balorian maccus', 'dying', 0, '{sourcename} says, "Lord Balor, I have failed you!"', 20, 'c', '2022-01-22 15:00:00', 'balorianmaccus-dying-balorfailedyou'),
	('balorian owin', 'dying', 0, '{sourcename} says, "Lord Balor, I have failed you!"', 20, 'c', '2022-01-22 15:00:00', 'balorianowin-dying-balorfailedyou'),
	('balorian tiertu', 'dying', 0, '{sourcename} says, "Lord Balor, I have failed you!"', 20, 'c', '2022-01-22 15:00:00', 'baloriantiertu-dying-balorfailedyou'),
	('Fusi', 'interact', 0, '{sourcename} says, "Meoow, Meeooooww!"', 50, 'c', '2021-10-20 13:49:45', 'be2be4f1-95c6-4d35-b632-7e404af4e7c8'),
	('Fusi', 'interact', 0, '{sourcename} says, "Meoow, Meeooooww!"', 50, 'c', '2021-10-20 13:53:53', 'c20279b0-261e-4e04-be94-739dd7e8a562'),
	('Atlas', 'interact', 25, '{sourcename} says, "Hey {targetname}, please help us and submit tickets in our forum to get faster to next test or release."', 25, 'c', '2021-11-20 17:14:11', 'c38d1c83-dcad-412b-8604-31b03560aef7'),
	('Server Out Yet?', 'interact', 0, '{sourcename} says, See you on June 24th Sharkb... err, {targetname}!', 100, 'c', '2022-05-20 09:21:11', 'cde90beb-8f7a-4653-bf33-306e9ed8beeb'),
	('Fusi', 'interact', 0, '{sourcename} says, "Purr Purrrrr!"', 100, 'c', '2021-10-20 13:49:22', 'ceeb270f-c36d-448c-af8b-4e7c8d1b9399'),
	('cliff dweller hunter', 'aggroing', 0, '{sourcename} says, "Whatever you\'ve got, I\'m sure we can use, {class}! This is our land, and you\'re not welcome here!"', 50, 'c', '2022-01-22 15:00:00', 'cliffdwellerhunter-aggroing-wecanuse'),
	('Fusi', 'roaming', 0, '{sourcename} says, "Meoow, Meeooooww!"', 50, 'c', '2021-10-20 13:50:08', 'd639d6f7-acd4-47ee-b8cd-b76fd3ed0e16'),
	('Pico', 'interact', 0, '{sourcename} says, "Pico small. Pico afraid of big demons. But Pico smart. Pico take stuffs from demons! Demons no try to hurt Pico with stuffs now, hehe! Pico give stuffs for diamond seals. Pico want diamond seals!"', 20, 'p', '2021-12-28 12:33:43', 'df-pico-greeting-picosmart'),
	('succubus', 'aggroing', 0, '{sourcename} says, "Come closer and feel my kiss."', 25, 'c', '2021-12-28 12:29:44', 'df-succubus-aggro-comecloser'),
	('Hamar', 'aggroing', 0, '{sourcename} says, "How dare you venture into my home! I will slice you apart!"', 100, 'c', '2021-12-28 12:40:47', 'dodens-hamar-aggro-sliceapart'),
	('Ella Johannson', 'interact', 0, '{sourcename} says, "Take a look around {class}. I am sure there is something here that will interest you."', 100, 'c', '2022-01-22 15:00:00', 'ellajohannson-greeting-takelookaround'),
	('far dorocha', 'dying', 0, '{sourcename} says, "Once our plans are in place, you will feel the true might of the Siabra!"', 50, 'c', '2022-01-22 15:00:00', 'fardorocha-dying-plansinplace'),
	('filidh', 'aggroing', 0, '{sourcename} says, "Cernunnos take thee!"', 30, 'c', '2022-01-22 15:00:00', 'filidh-aggroing-cernunnostakethee'),
	('filidh', 'dying', 0, '{sourcename} says, "The cycle of my life has ended. Let my rebirth be the seed of you undoing!"', 30, 'c', '2022-01-22 15:00:00', 'filidh-dying-rebirthseedundoing'),
	('filidh sacrificer', 'aggroing', 0, '{sourcename} says, "Cernunnos take thee!"', 30, 'c', '2022-01-22 15:00:00', 'filidh2-aggroing-cernunnostakethee'),
	('filidh sacrificer', 'dying', 0, '{sourcename} says, "The cycle of my life has ended. Let my rebirth be the seed of you undoing!"', 30, 'c', '2022-01-22 15:00:00', 'filidh2-dying-rebirthseedundoing'),
	('devout filidh', 'aggroing', 0, '{sourcename} says, "Cernunnos take thee!"', 30, 'c', '2022-01-22 15:00:00', 'filidh3-aggroing-cernunnostakethee'),
	('devout filidh', 'dying', 0, '{sourcename} says, "The cycle of my life has ended. Let my rebirth be the seed of you undoing!"', 30, 'c', '2022-01-22 15:00:00', 'filidh3-dying-rebirthseedundoing'),
	('Green Maw', 'aggroing', 0, '{sourcename} says, "I smell your foul blood, {targetname}. I long for its taste. Come, {class}, come to me."', 100, 'c', '2022-01-22 15:00:00', 'greenmaw-aggroing-ismellyou'),
	('gurite piller', 'dying', 0, '{sourcename} says, "You know nothing of our trials and tribulations within the Veil! Pathetic {race}! You will pay by the unseen hand of the Unseelie Court for your actions this day!"', 30, 'c', '2022-01-22 15:00:00', 'guritepiller-unseeliecourt'),
	('gurite seeker', 'dying', 0, '{sourcename} says, "You know nothing of our trials and tribulations within the Veil! Pathetic {race}! You will pay by the unseen hand of the Unseelie Court for your actions this day!"', 30, 'c', '2022-01-22 15:00:00', 'guriteseeker-aggroing-patheticrace'),
	('gurite seeker', 'dying', 0, '{sourcename} says, "Once our plans are in place, you will feel the true might of the Siabra!"', 30, 'c', '2022-01-22 15:00:00', 'guriteseeker-dying-mightofsiabra'),
	('Aelerogh', 'interact', 0, '{sourcename} says, "You needn\'t be an accomplished rider to ride these fine steeds. They\'ll get you to where you need to go. Just leave the driving to us!"', 50, 'c', '2022-01-22 15:00:00', 'hib-aelerogh-greeting-accomplishedrider'),
	('Aelerogh', 'interact', 0, '{sourcename} says, "Cut down on your travel time, friend! I have many fine horses that can speed your route to various destinations."', 50, 'c', '2021-12-28 11:50:48', 'hib-aelerogh-greeting-stablemaster'),
	('annoying lucradan', 'dying', 0, '{sourcename} says, "No!!! But I am invincible! I\'ll be back, you wait and see!"', 80, 'c', '2021-12-28 12:00:08', 'hib-annoyinglucradan-dying-illbeback'),
	('annoying lucradan', 'fighting', 0, '{sourcename} says, "You can\'t hurt me!"', 10, 'c', '2021-12-28 11:53:56', 'hib-annoyinglucradan-fighting-canthurtme'),
	('annoying lucradan', 'fighting', 0, '{sourcename} says, "No, don\'t hurt me!"', 10, 'c', '2022-01-22 15:00:00', 'hib-annoyinglucradan-fighting-donthurtme'),
	('balorian meisceoir', 'dying', 0, 'The balorian meisceoir staggers for the last time before collapsing with a thud.', 30, 's', '2022-01-22 15:00:00', 'hib-balorianmeisceoir-dying-staggerscollapsing'),
	('balorian meisceoir', 'roaming', 0, 'The balorian meisceoir tilts its head to the side and belches loudly, followed by a loud *HIC*.', 33, 'c', '2022-01-22 15:00:00', 'hib-balorianmeisceoir-roaming-belchesloudly'),
	('balorian meisceoir', 'roaming', 0, 'The balorian meisceoir takes a swig from its large tankard and staggers about pitifully.', 33, 'c', '2022-01-22 15:00:00', 'hib-balorianmeisceoir-roaming-swigfromtankard'),
	('cluricaun trip', 'seeing', 0, '{sourcename} says, "If you ever catch one of my leprechaun cousins, be sure you don\'t take your eyes off him. Leprechauns are quick!', 20, 'c', '2022-01-22 15:00:00', 'hib-clurican-seeing-leprechauntricky'),
	('curmudgeon crab-catcher', 'fighting', 0, '{sourcename} says, "Siabra not what you think! They out to rule all of Hibernia!"', 3, 'c', '2021-12-28 12:24:38', 'hib-crabcatcher-fighting-siabrarulehib'),
	('curmudgeon crab-catcher', 'roaming', 0, '{sourcename} says, "Siabra and Unseelie Court bad news! Never trust them!"', 25, 'c', '2021-12-28 12:24:38', 'hib-crabcatcher-roam-siabrabadnews'),
	('eriu henter', 'aggroing', 0, '{sourcename} says, "Do you think we do not know of Proinnsias\' plan to take the silver mines from us? Pathetic being, we are more superior than he could ever hope to be. Soon we shall rule all of Hibernia and no one, not even you, will be able to stop us!"', 10, 'c', '2022-01-22 15:00:00', 'hib-eriuhenter-aggroing-proinnsiasplan'),
	('Freagus', 'interact', 0, '{sourcename} says, "Cut down on your travel time, friend! I have many fine horses that can speed your route to various destinations."', 100, 'c', '2021-12-28 11:50:48', 'hib-freagus-greeting-stablemaster'),
	('Glimmer Orist', 'aggroing', 0, '{sourcename} says, "You have dared to enter the home of our King. I shall stop you here and now!"', 100, 'c', '2022-01-22 15:00:00', 'hib-glimmerorist-aggroing-ishallstopyou'),
	('granny', 'dying', 0, '{sourcename} says, "You rotten children! How could you do this to me?"', 20, 'c', '2022-01-22 15:00:00', 'hib-granny-dying-rottenchildren'),
	('Jahan', 'interact', 0, '{sourcename} says, "What may I do for you, brave {class}?"', 100, 'c', '2021-12-28 12:05:24', 'hib-jahan-greeting-whatcanido'),
	('Kylirean', 'interact', 0, '{sourcename} says, "What may I do for you, brave {class}?"', 100, 'c', '2021-12-28 12:05:24', 'hib-kylirean-greeting-whatcanido'),
	('leprechaun', 'killing', 0, '{sourcename} says, "Ho there. Methinks yer just a wee bit out of yer league. Mayhaps ye should head on back to yer mama\'s and come back when ye can handle the real world."', 30, 'c', '2021-12-28 12:40:47', 'hib-leprechaun-killing-outofyourleague'),
	('Marus', 'interact', 0, '{sourcename} says, "Good day to you, {class}."', 50, 'c', '2021-12-28 12:40:47', 'hib-marus-greeting-goodday'),
	('Master Ranger', 'aggroing', 0, '{sourcename} says, "They\'re here! Take aim and let your arrows fly swiftly into them!"', 100, 'c', '2021-12-28 12:40:47', 'hib-masterranger-aggro-letloose'),
	('Sentinel Moya', 'interact', 0, '{sourcename} says, "Greetings, {targetname}. What brings you to Ardee today?"', 100, 'c', '2021-12-28 12:10:35', 'hib-sentinelmoya-greeting-greetings'),
	('siabra mireguard', 'fighting', 0, '{sourcename} says, "You know nothing of our trials and tribulations within the Veil! Pathetic {race}! You will pay by the unseen hand of the Unseelie Court for your actions this day!"', 3, 'c', '2022-01-22 15:00:00', 'hib-siabramireguard-fighting-unseeliecourt'),
	('siabra venator', 'aggroing', 0, '{sourcename} says, "The Curmudgeons are nothing but filthy creatures. If you ally yourself with them, then you too must be exterminated!"', 30, 'c', '2022-01-22 15:00:00', 'hib-siabravenator-aggroing-curmudgeonsfilthy'),
	('siabra venator', 'dying', 0, '{sourcename} says, "Once our plans are in place, you will feel the true might of the Siabra!"', 20, 'c', '2022-01-22 15:00:00', 'hib-siabravenator-dying-truemight'),
	('siabra venator', 'dying', 0, '{sourcename} says, "Once our plans are in place, you will feel the true might of the Siabra!"', 30, 'c', '2022-01-22 15:00:00', 'hib-siabravenator-dying-truemightsiabra'),
	('siabra venator', 'fighting', 0, '{sourcename} says, "Bow before me, fool, for you will not last when we take over Hibernia!"', 3, 'c', '2022-01-22 15:00:00', 'hib-siabravenator-fighting-bowbeforeme'),
	('siabra venator', 'roaming', 0, '{sourcename} says, "The Unseelie Court will own all of Hibernia soon, and the Siabra will be at the heart of the power!"', 10, 'c', '2022-01-22 15:00:00', 'hib-siabravenator-seeing-heartofpower'),
	('siabra wayguard', 'aggroing', 0, '{sourcename} says, "The Curmudgeons are nothing but filthy creatures. If you ally yourself with them, then you too must be exterminated!"', 20, 'c', '2022-01-22 15:00:00', 'hib-siabrawayguard-aggroing-curmudgeonsfilthycreatures'),
	('Tadhg', 'seeing', 10, '{sourcename} says, "Greetings, young {class}."', 25, 'c', '2021-12-28 12:13:31', 'hib-tadhg-seeing-greetings'),
	('Waljan', 'interact', 0, '{sourcename} says, "If you came seeking the legendary healing powers of the elves, you have come to the right place. What ails you, my friend?"', 100, 'c', '2022-01-22 15:00:00', 'hib-waljan-greeting-legendaryhealingpowers'),
	('Kierac the Destroyer', 'killing', 0, '{sourcename} yells, "Do you see how futile it is to attack us now? Just as {targetname} fell, so shall you all!"', 20, 'y', '2022-01-22 15:00:00', 'kieracdestroyer-killing-soshallyouall'),
	('Melancholic Fairy Queen', 'aggroing', 0, '{sourcename} says, "Guards! Guards! You allowed aggressors inside our perimeter! Stop them, you miserable louts! They encroach upon our home, expulse them!"', 100, 'c', '2022-01-22 15:00:00', 'melancholicfairyqueen-aggroing-expulsethem'),
	('Aaric', 'interact', 0, '{sourcename} says, "Hail to ye, {class}! Surely you have a look about ya that says you only wield the finest steel! You need not look no further, I\'ve got what you need."', 100, 'c', '2022-01-22 15:00:00', 'mid-aaric-greeting-neednotlooknofurther'),
	('Alfgeirr', 'interact', 0, '{sourcename} says, "Whaddya want? Can\'t you see I\'m working here? Get lost, pipsqueak. I\'m busy."', 100, 'c', '2022-01-22 15:00:00', 'mid-alfgeirr-greeting-getlostpipsqueak'),
	('Alleca Gunderson', 'interact', 0, '{sourcename} says, "Hyndla\'s dyes are not in fashion this season. Give mine a try!"', 100, 'c', '2022-01-22 15:00:00', 'mid-allecagunderson-greeting-dyesnotinfashion'),
	('Amma', 'interact', 0, '{sourcename} says, "Hand me the item you want to enchant and I shall tell you what the cost will be."', 100, 'c', '2022-01-22 15:00:00', 'mid-amma-greeting-enchanter'),
	('Ander', 'interact', 0, '{sourcename} says, "A weapon isn\'t truly a weapon unless it has a bite. My poisons will give any weapon that bite!"', 50, 'c', '2022-01-22 15:00:00', 'mid-ander-greeting-poisonsgiveweaponbite'),
	('Ander', 'interact', 0, '{sourcename} says, "Hello there. Ander is my name and poisons are my game! If you need a poison to use on your enemies, you\'ve come to the right place! Oilibhear and I make and sell the finest poisons this side of Muspelheim, or at least that\'s what we think. We\'ve seen our poisoned used by some Shadowblades fighting Scout Argyle and they took him down quick. Poisons are the way to go!"', 50, 'p', '2022-01-22 15:00:00', 'mid-ander-interact-poisonsaremygame'),
	('Anya Vinsdottir', 'interact', 0, '{sourcename} says, "True power can only be harnessed through an item of focus!"', 100, 'c', '2022-01-22 15:00:00', 'mid-anya-vinsdottir-greeting-truepowerfocus'),
	('Armond', 'interact', 0, '{sourcename} says, "I got yer wares! What do ya want?"', 100, 'c', '2022-01-22 15:00:00', 'mid-armond-greeting-igotyerwares'),
	('Arnkatla', 'interact', 0, '{sourcename} says, "Please leave me in peace. I do not wish to speak to anyone."', 50, 'c', '2022-01-22 15:00:00', 'mid-arnkatla-greeting-leavemeinpeace'),
	('Arnkatla', 'interact', 0, 'Arnkatla looks around sadly.', 50, 'c', '2022-01-22 15:00:00', 'mid-arnkatla-greeting-looksaroundsadly'),
	('Arvakl Gerske', 'interact', 0, '{sourcename} says, "Hand me the object and I shall tell you how much it will cost to recharge it."', 100, 'c', '2022-01-22 15:00:00', 'mid-arvaklgerske-greeting-handmeobject'),
	('Arve', 'interact', 0, '{sourcename} says, "For a small fee, I can infuse your weapons or armor with an enchantment that will improve their quality. Just hand me the item. It must be of a material I can work with."', 100, 'c', '2022-01-22 15:00:00', 'mid-arve-greeting-forasmallfee'),
	('Asra', 'interact', 0, '{sourcename} says, "I got all the arrows you need right here! What are you looking for?"', 100, 'c', '2022-01-22 15:00:00', 'mid-asra-greeting-gotallthearrows'),
	('Auda', 'interact', 0, '{sourcename} says, "I got yer wares! What do ya want?"', 100, 'c', '2022-01-22 15:00:00', 'mid-auda-greeting-igotyerwares'),
	('Baldus', 'interact', 0, '{sourcename} says, "I got yer wares! What do ya want?"', 100, 'c', '2022-01-22 15:00:00', 'mid-baldus-greeting-igotyerwares'),
	('Barkeep Alaka', 'interact', 0, '{sourcename} says, "Hail, {class}! Are you here just to visit?"', 100, 'c', '2022-01-22 15:00:00', 'mid-barkeepalaka-greeting-heretovisit'),
	('Besje', 'interact', 0, '{sourcename} says, "Welcome to Huginfel, {class}. I do so hope you enjoy your stay here. I would like to help you out with anything you might need, but I am a little busy at this moment. Perhaps I can be of more help to you later. Good day!"', 100, 'p', '2022-01-22 15:00:00', 'mid-besje-greeting-welcometohuginfel'),
	('Bolli', 'interact', 0, 'Bolli limps about humming a dirge quietly to himself.', 100, 'c', '2022-01-22 15:00:00', 'mid-bolli-greeting-hummingadirge'),
	('Bothe', 'interact', 0, '{sourcename} says, "Want to buy somethin\'?"', 100, 'c', '2022-01-22 15:00:00', 'mid-bothe-greeting-wanttobuy'),
	('Brede', 'interact', 0, '{sourcename} says, "I got just what you need!"', 100, 'c', '2022-01-22 15:00:00', 'mid-brede-greeting-igotwhatyouneed'),
	('Brunhil', 'aggroing', 0, 'Brunhil screams, "GET OUT OF MY SHOP!"', 100, 'y', '2022-01-22 15:00:00', 'mid-brunhil-aggroing-getoutshop'),
	('Burl', 'interact', 0, '{sourcename} says, "I got just what you need!"', 100, 'c', '2022-01-22 15:00:00', 'mid-burl-greeting-igotwhatyouneed'),
	('Chieftain Guard', 'interact', 0, '{sourcename} says, "Good day to you, {targetname}."', 100, 'c', '2022-01-22 15:00:00', 'mid-chieftainguard-greeting-gooddaytoyou'),
	('Corath', 'interact', 0, '{sourcename} says, "Relax a bit and take a load off yer feet."', 100, 'c', '2022-01-22 15:00:00', 'mid-corath-greeting-relaxabit'),
	('Cornelis', 'emoting', 0, 'Cornelis looks up from his work, eyeing you for a second before speaking in a very rough, worn voice.', 100, 'c', '2022-01-22 15:00:00', 'mid-cornelis-emoting-looksupfromwork'),
	('Cornelis', 'interact', 0, '{sourcename} says, "Good day, {race}. You can purchase weapons from the other vendors here. These aren\'t quite ready yet."', 100, 'c', '2022-01-22 15:00:00', 'mid-cornelis-greeting-thesearentready'),
	('crazed lycantic', 'aggroing', 0, '{sourcename} says, "You...you did this to me! Aaaiieee!"', 50, 'c', '2022-01-22 15:00:00', 'mid-crazedlycantic-aggroing-youdidthistome'),
	('Digby', 'interact', 0, '{sourcename} says, "A solid piece of steel or wood between you and your enemy might help a bit. Give my shields a try!"', 100, 'c', '2022-01-22 15:00:00', 'mid-digby-greeting-solidpieceofsteel'),
	('dread commander', 'dying', 0, '{sourcename} says, "I have failed you, {controller}!"', 100, 'c', '2022-01-22 15:00:00', 'mid-dreadcommander-dying-failedyou'),
	('Durl', 'dying', 0, 'Durl tries to prop himself up with his spear as his life flows from him. After a few moments his grip on the weapon slips and his lifeless corpse flops to the ground.', 100, 's', '2022-01-22 15:00:00', 'mid-durl-dying-proponspear'),
	('Eigil', 'interact', 0, '{sourcename} says, "Would you like to buy something?"', 100, 'c', '2022-01-22 15:00:00', 'mid-eigil-greeting-liketobuysomething'),
	('Eirik', 'interact', 0, '{sourcename} says, "I have the finest staves around! Please, take a look!"', 100, 'c', '2022-01-22 15:00:00', 'mid-eirik-greeting-fineststaves'),
	('Enir', 'interact', 0, '{sourcename} says, "I got yer wares! What do ya want?"', 100, 'c', '2022-01-22 15:00:00', 'mid-enir-greeting-igotyerwares'),
	('Eryklan', 'interact', 0, '{sourcename} says, "Cut down on your travel time, friend! I have many fine horses that can speed your route to various destinations."', 100, 'c', '2022-01-22 15:00:00', 'mid-eryklan-greeting-stablemaster'),
	('Felisha', 'interact', 0, '{sourcename} says, "Cut down on your travel time, friend! I have many fine horses that can speed your route to various destinations."', 100, 'c', '2022-01-22 15:00:00', 'mid-felisha-greeting-stablemaster'),
	('Fianna', 'interact', 0, '{sourcename} says, "Want to buy somethin\'?"', 100, 'c', '2022-01-22 15:00:00', 'mid-fianna-greeting-wanttobuy'),
	('Findar', 'interact', 0, '{sourcename} says, "As you entrust your precious belongings to me, I shall guard them with my life."', 100, 'c', '2022-01-22 15:00:00', 'mid-findar-greeting-vaultkeeper'),
	('Frey', 'interact', 0, '{sourcename} says, "Would you like to buy something?"', 100, 'c', '2022-01-22 15:00:00', 'mid-frey-greeting-liketobuysomething'),
	('Galkvinne', 'interact', 0, '{sourcename} says, "I hope it doesn\'t rain. I recently noticed a small hole in my roof."', 100, 'c', '2022-01-22 15:00:00', 'mid-galkvinne-greeting-hopeitdoesntrain'),
	('Geirrid', 'interact', 0, '{sourcename} says, "Would you like to buy something?"', 100, 'c', '2022-01-22 15:00:00', 'mid-geirrid-greeting-liketobuysomething'),
	('Geoffrey Krath', 'interact', 0, '{sourcename} says, "I\'m tryin\' to have a conversation here. Get lost!"', 100, 'c', '2022-01-22 15:00:00', 'mid-geoffreykrath-greeting-conversationgetlost'),
	('Gerd', 'interact', 0, '{sourcename} says, "Plucked these feathers meself! Perfect for your arrow making, care to try a few?"', 100, 'c', '2022-01-22 15:00:00', 'mid-gerd-greeting-pluckedthesemeself'),
	('Goi Halfdan', 'interact', 0, '{sourcename} says, "Greetings {targetname} of the mighty {class} caste! I regret I have little time to chat with you this fine day. I must return to my studies. Safe travels to you and your friends."', 100, 'c', '2022-01-22 15:00:00', 'mid-goihalfdan-greeting-littletimetochat'),
	('Gregor', 'interact', 0, '{sourcename} says, "I got yer wares! What do ya want?"', 100, 'c', '2022-01-22 15:00:00', 'mid-gregor-greeting-igotyerwares'),
	('Grjotgard', 'aggroing', 0, 'Grjotgard growls loudly and attacks!', 100, 's', '2022-01-22 15:00:00', 'mid-grjotgard-aggroing-growlsloudly'),
	('Gudrid', 'interact', 0, '{sourcename} says, "Want to buy som\'din?"', 100, 'c', '2022-01-22 15:00:00', 'mid-gudrid-greeting-buysomdin'),
	('Gyda', 'interact', 0, '{sourcename} says, "Want to buy somethin\'?"', 100, 'c', '2022-01-22 15:00:00', 'mid-gyda-greeting-wanttobuy'),
	('Hallfred', 'interact', 0, '{sourcename} says, "Why am I still out here? Why, this is a prime spot to sell my weapons! I get all the travelers headed to Jordheim, plus it\'s quiet and the fresh air is nice. I plan to set up permanent shop here!"', 100, 'c', '2022-01-22 15:00:00', 'mid-hallfred-greeting-primespotsellweapons'),
	('Haylei', 'interact', 0, '{sourcename} says, "Can I interest you in any of my fine merchandise?"', 100, 'c', '2022-01-22 15:00:00', 'mid-haylei-greeting-caniinterestyou'),
	('Helga', 'interact', 0, '{sourcename} says, "I got just what you need!"', 100, 'c', '2022-01-22 15:00:00', 'mid-helga-greeting-igotwhatyouneed'),
	('Hrugnar', 'interact', 0, '{sourcename} says, "I got better hats than that fella over in the next town."', 100, 'c', '2022-01-22 15:00:00', 'mid-hrugnar-greeting-gotbetterhats'),
	('Hulda', 'interact', 0, '{sourcename} says, "Would you like to buy something?"', 100, 'c', '2022-01-22 15:00:00', 'mid-hulda-greeting-liketobuysomething'),
	('Idona Tiu', 'interact', 0, '{sourcename} says, "Welcome to my shop. I hope there\'s something I can help you find."', 100, 'c', '2022-01-22 15:00:00', 'mid-idonatiu-greeting-welcometoshop'),
	('Im', 'interact', 0, '{sourcename} says, "Protect your skin with the finest armors in all of Midgard!"', 100, 'c', '2022-01-22 15:00:00', 'mid-im-greeting-protectyourskin'),
	('Ime', 'interact', 0, '{sourcename} says, "Want to buy somethin\'?"', 100, 'c', '2022-01-22 15:00:00', 'mid-ime-greeting-wanttobuy'),
	('Ingirun', 'interact', 0, '{sourcename} says, "Hand me the object and I shall tell you how much it will cost to recharge it."', 100, 'c', '2022-01-22 15:00:00', 'mid-ingirum-greeting-recharge'),
	('Ivara', 'interact', 0, '{sourcename} says, "Want to buy somethin\'?"', 100, 'c', '2022-01-22 15:00:00', 'mid-ivara-greeting-wanttobuy'),
	('Halla', 'interact', 0, '{sourcename} says, "Hi there. I like this town. There are many things to do as long as you are smart and stay out of trouble."', 100, 'c', '2022-01-22 15:00:00', 'mid-ja;;a-greeting-ilikethistown'),
	('Jarl Yuliwyf', 'interact', 0, '{sourcename} says, "As you entrust your precious belongings to me, I shall guard them with my life."', 100, 'c', '2022-01-22 15:00:00', 'mid-jarlyuliwyf-greeting-entrustbelongings'),
	('Jolgeir', 'interact', 0, '{sourcename} says, "Now here\'s someone who shows proper respect for poisons. Have any interesting plans for this venom? I\'m kidding, I\'m kidding. I don\'t want to know what you\'re going to do with it!"', 100, 'c', '2022-01-22 15:00:00', 'mid-jolgeir-greeting-respectforpoisons'),
	('Jorun', 'interact', 0, '{sourcename} says, "Can I interest you in some of my fine brocade?"', 100, 'c', '2022-01-22 15:00:00', 'mid-jorun-greeting-finebrocade'),
	('Josli', 'interact', 0, '{sourcename} says, "Greetings to you. What might I sell to you today?"', 100, 'c', '2022-01-22 15:00:00', 'mid-josli-greeting-whatmightisell'),
	('Kalbin', 'interact', 0, '{sourcename} says, "Greetings, {race}. How may I be of service this day?"', 100, 'c', '2022-01-22 15:00:00', 'mid-kalbin-greeting-howbeofservice'),
	('Kappi', 'interact', 0, 'Kappi whimpers impatiently at Annudia.', 100, 'c', '2022-01-22 15:00:00', 'mid-kappi-greeting-whimpersimpatiently'),
	('Katrena Lettson', 'interact', 0, '{sourcename} says, "Greetings, {class}, and welcome to Knarr! I am Katrena and many say I am the one in charge of Knarr. I suppose that is true, for I keep an eye on the merchants and make sure the guards throw out anyone one causing trouble around here. My son and his wife tend the lighthouse on the other side of Knarr. You should speak to them if you can. I\'m sorry I can\'t chat longer, but I must read over this scroll. Svadi Tyrkirson sent this over. He wants to raise his prices, but don\'t worry, I won\'t let him!"', 100, 'p', '2022-01-22 15:00:00', 'mid-katrenalettson-interact-welcometoknarr'),
	('Kekov', 'interact', 0, '{sourcename} says, "What are you doing way out here? You\'re not with those savages are you?"', 100, 'c', '2022-01-22 15:00:00', 'mid-kekov-greeting-doingwayouthere'),
	('Kell', 'interact', 0, '{sourcename} says, "Can I help ya?"', 100, 'c', '2022-01-22 15:00:00', 'mid-kell-greeting-canihelpya'),
	('Kiarr', 'interact', 0, '{sourcename} says, "Kiarr at yer service, {class}! Gimme yer weapon and I shall make\'t new again, for only a wee fee!"', 100, 'c', '2022-01-22 15:00:00', 'mid-kiarr-greeting-weaponrepair'),
	('Kkor Borson', 'interact', 0, 'Kkor assesses you with sharp eyes.', 100, 'c', '2022-01-22 15:00:00', 'mid-kkorborson-greeting-sharpeyes'),
	('Kol Smithir', 'interact', 0, 'Kol Smithir ignores your request to see his wares as he continues to shape the fiery hot metal.', 100, 'c', '2022-01-22 15:00:00', 'mid-korsmithir-greeting-ignoresrequestwares'),
	('Kran', 'interact', 0, '{sourcename} says, "Good day my friend, can I help you?"', 100, 'c', '2022-01-22 15:00:00', 'mid-kran-greeting-canihelpyou'),
	('Kristen', 'interact', 0, 'Kristen raises her eyebrow at you.', 100, 'c', '2022-01-22 15:00:00', 'mid-kristen-greeting-raiseseyebrow'),
	('Kvasir', 'interact', 0, '{sourcename} greets you in a gruff voice.', 100, 'c', '2022-01-22 15:00:00', 'mid-kvasir-greeting-gruffvoice'),
	('Leim', 'interact', 0, '{sourcename} says, "You seek a good set of leggings, do you not?"', 100, 'c', '2022-01-22 15:00:00', 'mid-leim-greeting-goodsetleggings'),
	('Leros', 'interact', 0, 'Leros just glares at you.', 100, 'c', '2022-01-22 15:00:00', 'mid-leros-greeting-glaresatyou'),
	('Linna', 'interact', 0, '{sourcename} says, "Good day to you, {class}."', 100, 'c', '2022-01-22 15:00:00', 'mid-linna-greeting-gooddaytoyou'),
	('Lodin', 'interact', 0, '{sourcename} says, "I got just what you need!"', 100, 'c', '2022-01-22 15:00:00', 'mid-lodin-greeting-igotwhatyouneed'),
	('Londar', 'interact', 0, '{sourcename} says, "Greetings {targetname}!  What can I do for you?"', 100, 'c', '2022-01-22 15:00:00', 'mid-londar-greeting-whatcanido'),
	('Luikko', 'interact', 0, 'Luikko looks up from the note he is reading.', 100, 'c', '2022-01-22 15:00:00', 'mid-luikko-greeting-notehereading'),
	('Maerta', 'interact', 0, '{sourcename} says, "I\'m sure I\'ve got everything you need!"', 100, 'c', '2022-01-22 15:00:00', 'mid-maerta-greeting-everythingyouneed'),
	('Meklorka Lettson', 'interact', 0, '{sourcename} says, "Hello there, {class}. I\'m Meklorka. My Papa makes the best boats! Everyone comes to him when they need a boat. I make the sails for my Papa\'s boats! Momma and I work hard to make the sails. I better finish this one before Papa gets mad!"', 100, 'c', '2022-01-22 15:00:00', 'mid-meklorkalettson-greeting-papamakesboats'),
	('Morgen', 'interact', 0, '{sourcename} says, "I got all the arrows you need right here! What are you looking for?"', 100, 'c', '2022-01-22 15:00:00', 'mid-morgen-greeting-allthearrows'),
	('Morlin Caan', 'interact', 0, 'Morlin cleans his blade.', 100, 'c', '2022-01-22 15:00:00', 'mid-morlin-greeting-cleansblade'),
	('Nanna', 'interact', 0, '{sourcename} says, "My family has a long history in the healing arts, my mother taught me all that I know. What healing do you require?"', 100, 'c', '2022-01-22 15:00:00', 'mid-nanna-greeting-healingarts'),
	('Njal', 'interact', 0, '{sourcename} says, "Chainmail is the finest armor you can buy in all the land! It\'s too bad that not everyone can wear chain. Even if you can\'t wear it, buy a piece and support me and my family!"', 100, 'c', '2022-01-22 15:00:00', 'mid-njal-greeting-chainmailfinestarmor'),
	('Oilibhear', 'interact', 0, '{sourcename} says, "Need a bit of an edge in combat? Try my poisons."', 100, 'c', '2022-01-22 15:00:00', 'mid-oilibhear-greeting-trymypoisons'),
	('Olav', 'interact', 0, '{sourcename} says, "Would you like to buy something?"', 100, 'c', '2022-01-22 15:00:00', 'mid-olav-greeting-liketobuysomething'),
	('Omolf Thorrison', 'interact', 0, '{sourcename} says, "Cut down on your travel time, friend!  I have many fine horses that can speed your route to various destinations."', 100, 'c', '2022-01-22 15:00:00', 'mid-omolf-greeting-stablemaster'),
	('Orm', 'interact', 0, '{sourcename} says, "Want to buy somethin\'?"', 100, 'c', '2022-01-22 15:00:00', 'mid-orm-greeting-wanttobuy'),
	('Ottar', 'interact', 0, '{sourcename} says, "Some of the mightiest and most ancient trees of Myrkwood have been felled for these materials. You\'ll not find better lumber anywhere."', 100, 'c', '2022-01-22 15:00:00', 'mid-ottar-greeting-ancienttrees'),
	('Ozur', 'interact', 0, '{sourcename} says, "Need a fresh start? Try a new color!"', 100, 'c', '2022-01-22 15:00:00', 'mid-ozur-greeting-needfreshstart'),
	('Pater', 'interact', 0, '{sourcename} says, "Is there something you\'re interested in?"', 100, 'c', '2022-01-22 15:00:00', 'mid-pater-greeting-somethinginterested'),
	('Radgar', 'interact', 0, '{sourcename} says, "Would you like to buy something?"', 100, 'c', '2022-01-22 15:00:00', 'mid-radgar-greeting-liketobuysomething'),
	('Ragnar', 'interact', 0, '{sourcename} says, "Would you like to buy something?"', 100, 'c', '2022-01-22 15:00:00', 'mid-ragnar-greeting-liketobuysomething'),
	('Rognvald', 'interact', 0, '{sourcename} says, "Please leave me alone. I am waiting for a sign from my god, Mimir. I must have quiet for that."', 100, 'c', '2022-01-22 15:00:00', 'mid-rognvald-greeting-leavemealone'),
	('Rorik', 'interact', 0, '{sourcename} says, "{class}! I have the best axes in all Svealand. My store stands ready!"', 100, 'c', '2022-01-22 15:00:00', 'mid-rorik-greeting-bestaxessvealand'),
	('Runolf', 'interact', 0, '{sourcename} says, "{class}! Come now! I know you could use a shield, no?"', 100, 'c', '2022-01-22 15:00:00', 'mid-runolf-greeting-useashieldno'),
	('Seiml', 'interact', 0, '{sourcename} says, "You are looking quite well, {class}. How can I be of service?"', 100, 'c', '2022-01-22 15:00:00', 'mid-seiml-greeting-howcaniservice'),
	('Sela Gorgunsonn', 'interact', 0, '{sourcename} says, "Welcome to my shop. Let me know if there\'s anything I can show you."', 100, 'c', '2022-01-22 15:00:00', 'mid-selagorgunsonn-greeting-welcomemyshop'),
	('Sentry', 'interact', 0, '{sourcename} says, "What are you looking at? Move along."', 100, 'c', '2022-01-22 15:00:00', 'mid-sentry-greeting-movealong'),
	('Sentry Thomas', 'interact', 0, '{sourcename} says, "Nothing to see here. Please move along."', 100, 'c', '2022-01-22 15:00:00', 'mid-sentrythomas-greeting-movealong'),
	('Sijur Halfdan', 'interact', 0, '{sourcename} says, "Greetings, {targetname}. I have little time to banter with you, as I have work that needs to be done. Perhaps, when the time is right, I will be able to discuss the affairs of Midgard with you more. Safe travels to you and your friends mighty {class}."', 100, 'c', '2022-01-22 15:00:00', 'mid-sijurhalfdan-greeting-littletimebanter'),
	('Sinmora', 'interact', 0, '{sourcename} says, "Good day to you, {class}."', 100, 'c', '2022-01-22 15:00:00', 'mid-sinmora-greeting-gooddaytoyou'),
	('Sinna Redtoes', 'interact', 0, 'Sinna looks up from the map she is drawing and glares at you.', 100, 'c', '2022-01-22 15:00:00', 'mid-sinnaredtoes-greeting-looksupfrommap'),
	('Snarrf', 'interact', 0, '{sourcename} says, "Good day. I\'m just waiting for the supplies to get here."', 100, 'c', '2022-01-22 15:00:00', 'mid-snarrf-greeting-waitingforsupplies'),
	('Solveig', 'interact', 0, '{sourcename} says, "Make a name for yourself! Buy my brightest colors!"', 100, 'c', '2022-01-22 15:00:00', 'mid-solveig-greeting-brightestcolors'),
	('Sonja Varinasdottir', 'interact', 0, '{sourcename} says, "Hand me the object and I shall tell you how much it will cost to recharge it."', 100, 'c', '2022-01-22 15:00:00', 'mid-sonjavarinasdottir-greeting-recharge'),
	('Arskar', 'interact', 0, '{sourcename} says, "Cut down on your travel time, friend! I have many fine horses that can speed your route to various destinations."', 100, 'c', '2022-01-22 15:00:00', 'mid-stablemaster-greeting-cutdowntravel'),
	('Svala', 'interact', 0, '{sourcename} says, "Want to buy somethin\'?"', 100, 'c', '2022-01-22 15:00:00', 'mid-svala-greeting-wanttobuy'),
	('Tait', 'interact', 0, '{sourcename} says, "Hail, brave citizen of Midgard!"', 50, 'c', '2022-01-22 15:00:00', 'mid-tait-greeting-hailcitizen'),
	('Tait', 'interact', 0, '{sourcename} says, "Trust me. You will strike fear into the hearts of all who oppose you with these."', 50, 'c', '2022-01-22 15:00:00', 'mid-tait-greeting-trustme'),
	('Thesill', 'interact', 0, '{sourcename} says, "Greetings, {race}. I am Thesill of Jordheim. What is your name, young one?"', 100, 'c', '2022-01-22 15:00:00', 'mid-thesill-greeting-thesillofjordheim'),
	('Thora', 'interact', 0, '{sourcename} says, "Greetings, {class}. How may I help you?"', 100, 'c', '2022-01-22 15:00:00', 'mid-thora-greeting-howhelpyou'),
	('Thord', 'interact', 0, '{sourcename} says, "I got yer wares! What do ya want?"', 100, 'c', '2022-01-22 15:00:00', 'mid-thord-greeting-igotyerwares'),
	('Tora', 'interact', 0, '{sourcename} says, "Lo there, do I see a fierce {class} before me! Imagine how much stronger you\'ll be in battle with one of my totems!"', 100, 'c', '2022-01-22 15:00:00', 'mid-tora-greeting-strongertotems'),
	('Torg the Hunter', 'fighting', 0, 'Torg seems to be unimpressed by his opponent, {targetname}!', 3, 's', '2022-01-22 15:00:00', 'mid-torgthehunter-fighting-unimpressed'),
	('Torrad Gunderson', 'interact', 0, '{sourcename} says, "If you\'re a caster, you shouldn\'t pass up the chance to wear my armor!"', 100, 'c', '2022-01-22 15:00:00', 'mid-torradgunderson-greeting-wearmyarmor'),
	('Trak', 'interact', 0, '{sourcename} says, "Good day. I\'m just waiting for the supplies to get here."', 100, 'c', '2022-01-22 15:00:00', 'mid-trak-greeting-waitingforsupplies'),
	('Uger', 'aggroing', 0, 'Uger pauses a moment and smirks as though his opponent {targetname} posed no threat to him!', 100, 's', '2022-01-22 15:00:00', 'mid-uger-aggroing-pausesmirk'),
	('Vahn', 'interact', 0, '{sourcename} says, "I can repair weapons or armor for you. Just hand me the item you want repaired and I\'ll see what I can do, for a small fee."', 100, 'c', '2022-01-22 15:00:00', 'mid-vahn-greeting-smithrepair'),
	('Vhig', 'interact', 0, '{sourcename} says, "Good day. I\'m just waiting for the supplies to get here."', 100, 'c', '2022-01-22 15:00:00', 'mid-vhig-greeting-waitingforsupplies'),
	('Vidar', 'interact', 0, '{sourcename} says, "Would you like to buy something?"', 100, 'c', '2022-01-22 15:00:00', 'mid-vidar-greeting-liketobuysomething'),
	('Viking Butescarl', 'interact', 0, '{sourcename} says, "Good day to you, {targetname}."', 100, 'c', '2022-01-22 15:00:00', 'mid-vikingbutescarl-greeting-gooddaytoyou'),
	('Viking Dreng', 'interact', 0, '{sourcename} says, "Good day to you, {targetname}."', 100, 'c', '2022-01-22 15:00:00', 'mid-vikingdreng-greeting-gooddaytoyou'),
	('Viking Gestr', 'interact', 0, '{sourcename} says, "Good day to you, {targetname}."', 100, 'c', '2022-01-22 15:00:00', 'mid-vikinggestr-greeting-gooddaytoyou'),
	('Viking Kreimhilde', 'interact', 0, '{sourcename} says, "Good day to you, {targetname}."', 100, 'c', '2022-01-22 15:00:00', 'mid-vikinghreimhilde-greeting-gooddaytoyou'),
	('Viking Hyndla', 'interact', 0, '{sourcename} says,"Good day to you."', 100, 'c', '2022-01-22 15:00:00', 'mid-vikinghyndla-greeting-gooddaytoyou'),
	('werewolf churl', 'aggroing', 0, '{sourcename} says, "Hwrr! You not can be here!"', 40, 'c', '2022-01-22 15:00:00', 'mid-werewolfchurl-aggroing-notcanbehere'),
	('werewolf churl', 'dying', 0, '{sourcename} says, "Bite... me..."', 40, 'c', '2022-01-22 15:00:00', 'mid-werewolfchurl-dying-biteme'),
	('wolfaur quixot', 'aggroing', 0, '{sourcename} says, "We are wolves of the dark caves, we are strong and we are brave!"', 30, 'c', '2022-01-22 15:00:00', 'mid-wolfaurquixot-aggroing-wolvesdarkcaves'),
	('Wulfwer', 'interact', 0, '{sourcename} says, "Want to buy somethin\'?"', 100, 'c', '2022-01-22 15:00:00', 'mid-wulfwer-greeting-wanttobuy'),
	('Salisbury giant', 'killing', 0, '{sourcename} says, "That was fun!"', 100, 'c', '2022-01-22 15:00:00', 'salisburygiant-killing-thatwasfun'),
	('siabra archmagi', 'aggroing', 0, '{sourcename} says, "Bow before me, fool, for you will not last when we take over Hibernia!"', 50, 'c', '2022-01-22 15:00:00', 'siabraarchmagi-aggroing-bowbeforeme'),
	('siabra venator', 'dying', 0, '{sourcename} says, "You know nothing of our trials and tribulations within the Veil! Pathetic {race}! You will pay by the unseen hand of the Unseelie Court for your actions this day!"', 30, 'c', '2022-01-22 15:00:00', 'siabravenator-unseeliecourt');
/*!40000 ALTER TABLE `mobxambientbehaviour` ENABLE KEYS */;

