/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE TABLE IF NOT EXISTS `playerxeffect` (
  `IsHandler` tinyint(1) NOT NULL DEFAULT 0,
  `Var6` int(11) NOT NULL DEFAULT 0,
  `Var5` int(11) NOT NULL DEFAULT 0,
  `Var4` int(11) NOT NULL DEFAULT 0,
  `Var3` int(11) NOT NULL DEFAULT 0,
  `Var2` double NOT NULL DEFAULT 0,
  `Var1` int(11) NOT NULL DEFAULT 0,
  `Duration` int(11) NOT NULL DEFAULT 0,
  `EffectType` text DEFAULT NULL,
  `SpellLine` text DEFAULT NULL,
  `ChardID` varchar(255) DEFAULT NULL,
  `LastTimeRowUpdated` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `PlayerXEffect_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`PlayerXEffect_ID`),
  KEY `I_PlayerXEffect_ChardID` (`ChardID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

/*!40000 ALTER TABLE `playerxeffect` DISABLE KEYS */;
/*!40000 ALTER TABLE `playerxeffect` ENABLE KEYS */;

